name: Dispatch Firmware Releases

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['WolfControl/gateway_wifi', 'WolfControl/gateway_espnow', 'WolfControl/sensor_water', 'WolfControl/sensor_atmosphere']
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CICD_KEY }}
          repository: ${{ matrix.repo }}
          event-type: 'esp-library-release'
          client-payload: '{
            "version": "${{ github.event.release.tag_name }}",
            "library": "${{ github.event.repository.name }}"
            }'
